template-file-path: bkp-wrkld-acct-roles.yaml

parameters: 
    HashKeyElementName: table2
    HashKeyElementType: S
    ReadCapacityUnits: 5
    WriteCapacityUnits: 5

tags:
    cost-center: '123456'
    org: 'AWS'
