template-file-path: bkp-wrkld-acct-roles.yaml

parameters: 
    HashKeyElementName: table2
    HashKeyElementType: elementtype
    ReadCapacityUnits: 4
    WriteCapacityUnits: 4

tags:
    cost-center: '123456'
    org: 'AWS'
